// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
#deprecated("use `@math.sin` instead")
#coverage.skip
pub fn Double::sin(self : Double) -> Double = "Math" "sin"

///|
#deprecated("use `@math.cos` instead")
#coverage.skip
pub fn Double::cos(self : Double) -> Double = "Math" "cos"

///|
#deprecated("use `@math.tan` instead")
#coverage.skip
pub fn Double::tan(self : Double) -> Double = "Math" "tan"

///|
#deprecated("use `@math.asin` instead")
#coverage.skip
pub fn Double::asin(self : Double) -> Double = "Math" "asin"

///|
#deprecated("use `@math.acos` instead")
#coverage.skip
pub fn Double::acos(self : Double) -> Double = "Math" "acos"

///|
#deprecated("use `@math.atan` instead")
#coverage.skip
pub fn Double::atan(self : Double) -> Double = "Math" "atan"

///|
#deprecated("use `@math.atan2` instead")
#coverage.skip
pub fn Double::atan2(self : Double, x : Double) -> Double = "Math" "atan2"
