// Copyright 2026 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
/// Min value constant for this type.
pub const MIN_VALUE : UInt64 = 0UL

///|
/// Min value constant for this type.
#deprecated("Use `MIN_VALUE` instead")
pub let min_value : UInt64 = 0UL

///|
/// Max value constant for this type.
pub const MAX_VALUE : UInt64 = 18446744073709551615UL

///|
/// Max value constant for this type.
#deprecated("Use `MAX_VALUE` instead")
pub let max_value : UInt64 = 18446744073709551615UL
